# Generated by Django 4.2.9 on 2024-10-19 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_client_compnay"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Compnay",
            new_name="Company",
        ),
        migrations.AddField(
            model_name="client",
            name="compnay",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="company_of_user",
                to="users.company",
                verbose_name="Company of user",
            ),
        ),
    ]
