# Generated by Django 4.2.9 on 2024-10-20 19:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_remove_client_company_clientcompany"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="companies",
            field=models.ManyToManyField(
                related_name="clients",
                through="users.ClientCompany",
                to="users.company",
            ),
        ),
    ]
